version: "3.9"
services:
  postgres-vaadin:
    container_name: postgres-vaadin
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vaadindb
    ports:
      - "5433:5432"